Modules/Inventory/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('inventory')->group(function() {
Route::group(['prefix'=>'inventory',
'middleware'=>['auth']
],function(){
    Route::resource('purchase','InventoryController');
    Route::post('create-customer-card','CardController@createCustomerCard')->name('create-customer-card');
    Route::resource('membership','MembershipController');
    Route::resource('rewards','RewardController');
    Route::resource('cards','CardController');
    Route::resource('gifts','GiftController');
    Route::post('gifts-check','GiftController@checkCustomerGift')->name('gifts-check');
    Route::post('membership-check','CardController@membershipCheck')->name('membership-check');
});

Modules/Inventory/Http/Controllers/GiftController.php
<?php

namespace Modules\Inventory\Http\Controllers;

use Exception;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Customer\Interfaces\CustomerInterface;
use Modules\Inventory\Interfaces\RewardInterface;
use Modules\Inventory\Interfaces\CardInterface;
use Modules\Inventory\Http\Requests\GiftCustomerRequest;
use Illuminate\Support\Facades\DB;

class GiftController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function __construct(RewardInterface $rewardInterface, CustomerInterface $customerInterface, CardInterface $cardInterface)
    {
        $this->rewardInterface = $rewardInterface;
        $this->customerInterface = $customerInterface;
        $this->cardInterface = $cardInterface;
    }
    public function index()
    {
        $data['customers'] = $this->customerInterface->with(['rewards'])->whereHas('rewards')->get();
        // dd($data['customers'][0]->rewards[0]->pivot->point_amt);
        return view('inventory::gifts.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        $data['customers'] = $this->customerInterface->with(['rewards'])->whereHas('card')->pluck('name', 'id');
        // dd( $data['customers']);
        $data['rewards'] = $this->rewardInterface->pluck('name', 'id');
        return view('inventory::gifts.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(GiftCustomerRequest $request)
    {
        // dd($request->all());
        try {
            DB::beginTransaction();
            $customer = $this->customerInterface->with('card')->findOrFail($request->customer_id);
            $customerRewardPoints = $customer->card->rewards_point;
            $reward = $this->rewardInterface->findOrFail($request->reward_id);
            $giftdata=[
                'reward_id'=>$request->reward_id,
                'point_amt'=>$customerRewardPoints
            ];
            // dd($giftdata, $customer);
            // $card = $this->cardInterface->findOrFail($customer->card->id);
            // dd($card, $reward);
            // if ($card->rewards_point >= $reward->point_worth) {
                //     $card->rewards_point = $card->rewards_point-$reward->point_worth;
                //     $card->save();
                // }
                if (is_null($customerRewardPoints)) {
                    return redirect()->back()->with('message', 'Customer is not eligiable to recieve Gifts');
                } else {
                    // dd('customer less more');
                    $customer->rewards()->attach($request->reward_id,['point_amt'=>$customerRewardPoints]);
                // return response(['error' => $customer->name . 'does not Have enough reward points']);
            }
        } catch (Exception $e) {

            DB::rollback();

            return response($e->getMessage());
        }
        DB::commit();
        return redirect()->route('gifts.index')->with('message', 'Gift Allocated To Customer Successfully');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('inventory::gifts.show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('inventory::gifts.edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }

    public function checkCustomerGift(Request $request)
    {
        // dd($request->all());
        $customer = $this->customerInterface->with(['card', 'rewards'])->findOrFail($request->customer_id);
        $customerRewardPoints = $customer->card->rewards_point - $customer->rewards->sum('point_worth');
        // dd($customerRewardPoints);
        $reward = $this->rewardInterface->findOrFail($request->reward_id);
        // dd($customer->card->rewards_point,$reward->point_worth);
        if ($customerRewardPoints < $reward->point_worth) {
            // dd('customer less more');
            return response(['error' => $customer->name . 'does not Have enough reward points']);
        } else {
            return response(['success' => 'success']);
        }

        // $rewards=$this->rewardInterface->pluck('name','id');
    }
}

Modules/Inventory/Resources/views/gifts/common.blade.php
{{-- @dd($customer) --}}
<div class="row">
    <div class="col-md-12">

        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-3 col-form-label">Choose Gift<span class="redAstrick"> *</span>:</label>
            <div class="col-sm-9">
                
                {!! form::select('reward_id', $rewards, null, ['class' => 'form-control', 'id' => 'reward_id', 'placeholder' => 'Choose Gift', 'required']) !!}


            </div>
        </div>
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-3 col-form-label">Customer<span class="redAstrick"> *</span>:</label>
            <div class="col-sm-9">
                {!! form::select('customer_id', $customers, null, ['class' => 'form-control', 'id' => 'customer_id', 'placeholder' => 'Customer', 'required']) !!}
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group mb-0 justify-content-end row">
            <div class="col-sm-9">
                <button type="submit" class="btn btn-info waves-effect waves-light float-right" id="submitBtn">Submit</button>
            </div>
        </div>
    </div>
</div>

Modules/Inventory/Resources/views/gifts/create.blade.php
@extends('dashboard::newLayouts.master')
@section('title')
    Create Customer Gifts
@endsection
@section('style')
{{-- <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"
type="text/css" /> --}}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
    .toast-message{
        color:black;
    }
</style>
@endsection

@section('content')
    {{-- @dd($customers) --}}
    <div class="container-fluid flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>

                <li class="breadcrumb-item"><a href="{{ route('gifts.index') }}">Gifts</a></li>
                <li class="breadcrumb-item active">Issue Customer Gifts</li>
            </ol>
        </div>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="col-12">
            <div class="card-box">
                <h4 class="mt-0 mb-3 header-title">Gifts</h4>
                {!! Form::open(['route' => 'gifts.store', 'method' => 'post', 'class' => 'needs-validation form-horizontal', 'novalidate', 'id' => 'formValidation']) !!}
                @include('inventory::gifts.common')
                {!! Form::close() !!}
            </div> <!-- end card-box -->
        </div>
    </div>
    </div>
@endsection
@section('script')
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script> --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function() {
            @if (Session::has('message'))
                toastr.success('{{ Session::get('message') }}')
            @endif
            @if (Session::has('error'))
                toastr.warning('{{ Session::get('error') }}')
            @endif
            // $(document).on('click', '#submitBtn', function() {
            //     var customer = $('#customer_id').val();
            //     var reward = $('#reward_id').val();
            //     $.ajax({
            //         type: "post",
            //         url: "{{ route('gifts-check') }}",
            //         data: {
            //             'customer_id': customer,
            //             'reward_id': reward,
            //             '_token' : "{{ csrf_token() }}",
            //         },
            //         context: this,
            //         success: function(response) {
            //             console.log(response)
            //             if (response.error) {
            //                 toastr["error"](response.error)
            //             }
            //             if (response.success) {
            //                 $('#formValidation').submit()
            //             }
            //         },
            //         errors: function(error) {

            //         },

            //     });
            // })
        })
    </script>
@endsection

Modules/Inventory/Resources/views/gifts/edit.blade.php
@extends('dashboard::newLayouts.master')
@section('title')
    Customer Create
@endsection
@section('content')
{{-- @dd($customer) --}}
<div class="container-fluid flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>

                <li class="breadcrumb-item"><a href="{{ route('customers.index') }}">Customers</a></li>
                <li class="breadcrumb-item active">Create Customer</li>
            </ol>
        </div>
        <div class="col-12">
            <div class="card-box">
                <h4 class="mt-0 mb-3 header-title">Edit Customer</h4>
                {!! Form::open(['route'=>['customers.update',$customer->id], 'method' => 'post', 'class' => 'needs-validation form-horizontal', 'novalidate','id'=>'formValidation']) !!}
                @method('PATCH')
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Full Name <span class="redAstrick"> *</span>:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="name" placeholder="Full Name" name="name" required value="{{$customer->name}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Email<span class="redAstrick"> *</span>:</label>
                            <div class="col-sm-9">
                                <input type="email" class="form-control" id="email" placeholder="Email" name="email" required value="{{$customer->email}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Aniversary Date:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="aniversary_date" placeholder="Aniversary Date" name="aniversary_date" value="{{$customer->customerDetails->aniversary_date}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Spouse Name:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="spouse_name" placeholder="Spouse Name" name="spouse_name" value="{{$customer->customerDetails->spouse_name}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Mobile:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="mobile" placeholder="Mobile" name="mobile"  value="{{$customer->customerDetails->mobile}}">
                            </div>
                        </div>
                        
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Phone<span class="redAstrick"> *</span>:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="phone" placeholder="Phone" name="phone" required   value="{{$customer->phone}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Address<span class="redAstrick"> *</span>:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="address" placeholder="Address" name="address" required  value="{{$customer->address}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Birth Date:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="birth_date" placeholder="Birth Date" name="birth_date" value="{{$customer->customerDetails->birth_date}}">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-3 col-form-label">Designation:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="designation" placeholder="Designation" name="designation" value="{{$customer->customerDetails->designation}}">
                            </div>
                        </div>
                        <div class="form-group mb-0 justify-content-end row">
                            <div class="col-sm-9">
                                <button type="submit" class="btn btn-info waves-effect waves-light float-right">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div> <!-- end card-box -->
        </div>
    </div>
    </div>
@endsection
@section('script')
@endsection

Modules/Inventory/Resources/views/gifts/index.blade.php
@extends('dashboard::newLayouts.master')
@section('title')
    Gifts History
@endsection
@section('style')
    <!-- third party css -->
    <link href="{{ Module::asset('dashboard:libs/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ Module::asset('dashboard:libs/datatables/responsive.bootstrap4.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ Module::asset('dashboard:libs/datatables/buttons.bootstrap4.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ Module::asset('dashboard:libs/datatables/select.bootstrap4.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"
        type="text/css" />
    <!-- third party css end -->
@endsection
@section('content')
<div class="container-fluid flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>

                <li class="breadcrumb-item active">Gifts History</li>
            </ol>
        </div>
        <div class="col-12">
            <div class="card-box table-responsive">
                <h4 class="mt-0 header-title">Gifts History</h4>
                

                <table id="responsive-customers" class="table table-bordered table-bordered  nowrap">
                    <a class="btn btn-sm btn-info float-right" href="{{ route('gifts.create') }}"> <i
                            class="fa fa-plus"> </i> </a>

                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Customer</th>
                            <th>Gift</th>
                            <th>At Reward Point</th>
                            {{-- <th>Action</th> --}}
                        </tr>
                    </thead>
                    <tbody>
                        {{-- @dd($customers) --}}
                        @foreach ($customers as $customer)
                            <tr>
                                <td>{{ $loop->index + 1 }}</td>
                                <td>{{ $customer->name }}</td>
                                <td>
                                   @foreach ($customer->rewards as $reward)
                                   <span class="badge badge-info">{{$reward->name}}</span>
                                   @endforeach
                                </td>
                                <td>
                                   @foreach ($customer->rewards as $reward)
                                   {{-- @dd($reward) --}}
                                   <span class="badge badge-warning">{{$reward->pivot->point_amt}}</span>
                                   @endforeach
                                </td>
                                {{-- <td>
                                    <a class="btn btn-info btn-sm " href="{{route('cards.edit',$card->id)}}"
                                        >
                                        <i class="fa fa-edit">
                                        </i>
                                    </a>
                                    <a href="javascript:void(0);" class="btn btn-sm btn-danger delete"
                                                data-id="{{ $card->id }}"><i class="fas fa-trash"></i></a>
                                            &nbsp; &nbsp;
                                            <form class="postdestroy" id="form_{{ $card->id }}" style="margin: 0;"
                                                method="Post" action="{{ route('cards.destroy', $card->id) }}"
                                                data-toggle="modal" data-target="#exampleModal">
                                                @csrf
                                                @method('Delete')
                                            </form>



                                </td> --}}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- end row -->
    </div> <!-- end row -->
@endsection
@section('script')
    <!-- third party js -->
    <script src="{{ Module::asset('dashboard:libs/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.responsive.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.buttons.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/buttons.html5.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/buttons.flash.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/buttons.print.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.select.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/pdfmake/pdfmake.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/pdfmake/vfs_fonts.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <!-- third party js ends -->
    <script>
        $(document).ready(function() {

            $('#responsive-customers').DataTable();
            @if (Session::has('message'))
                toastr.success('{{ Session::get('message') }}')
            @endif
            @if (Session::has('error'))
                toastr.warning('{{ Session::get('error') }}')
            @endif
            $(document).on('click', '.delete', function() {
                id = $(this).data('id');
                swal({
                        title: "Are you sure?",
                        text: "Once deleted, you will not be able to recover this data!",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (willDelete) {
                            $('#form_' + id).submit();
                            swal("Poof! Your record has been deleted!", {
                                icon: "success",

                            });
                        } else {
                            swal("Deleting Data Cancled!!");
                        }
                    });
            })

        })
    </script>
@endsection

Modules/Inventory/Resources/views/gifts/show.blade.php
@extends('dashboard::newLayouts.master')
@section('title')
    Customer Details- {{ $customer->name }}
@endsection
@section('content')
    {{-- @dd($customer) --}}
    <div class="container-fluid flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>

                <li class="breadcrumb-item "><a href="{{ route('dashboard.index') }}">Customers</a></li>
                <li class="breadcrumb-item active">{{ $customer->name }}</li>
            </ol>
        </div>
        <div class="col-12">
            <div class="card-box task-detail">
                
                <div class="row task-dates mb-0 mt-2">
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Customer Name</h5>
                        <p> {{ $customer->name }} <small class="text-muted"></small></p>
                    </div>

                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Phone No.</h5>
                        <p> {{ $customer->phone }} <small class="text-muted"></small></p>
                    </div>
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Email</h5>
                        <p>{{ $customer->email }}</p>
                    </div>

                </div>
                <div class="row task-dates mb-0 mt-2">
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Address</h5>
                        <p> {{ $customer->address }}
                            <small class="text-muted"></small>
                        </p>
                    </div>

                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Aniversary Date</h5>
                        <p>{{ $customer->customerDetails->aniversary_date }} <small class="text-muted"></small>
                        </p>
                    </div>
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Spouse Name</h5>
                        <p> {{ $customer->customerDetails->spouse_name }} <small class="text-muted">g</small></p>
                    </div>
                </div>
                <div class="row task-dates mb-0 mt-2">
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Birth Date</h5>
                        <p> {{ $customer->customerDetails->birth_date }}
                            <small class="text-muted"></small>
                        </p>
                    </div>

                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Mobile</h5>
                        <p> {{ $customer->customerDetails->mobile }}</p>
                    </div>
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Designation</h5>
                        <p>{{ $customer->customerDetails->designation }}</p>
                    </div>
                </div>

                <hr>
                <div class="form-group mb-0 justify-content-end row">
                    <div class="col-sm-9">
                        <a href="{{route('customers.index')}}" class="btn btn-info waves-effect waves-light float-right">Back</a>
                        <a href="{{route('customers.edit',$customer->id)}}" class="btn btn-warning waves-effect waves-light float-right mr-2" style="color:black;">Update</a>
                    </div>
                </div>

            </div>
        </div><!-- end col -->

    </div>
    </div>
    <!-- end row -->
@endsection