Modules/Inventory/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('inventory')->group(function() {
Route::group(['prefix'=>'inventory',
'middleware'=>['auth']
],function(){
    Route::resource('purchase','InventoryController');
    Route::post('create-customer-card','CardController@createCustomerCard')->name('create-customer-card');
    Route::resource('membership','MembershipController');
    Route::resource('rewards','RewardController');
    Route::resource('cards','CardController');
    Route::resource('gifts','GiftController');
    Route::post('gifts-check','GiftController@checkCustomerGift')->name('gifts-check');
    Route::post('membership-check','CardController@membershipCheck')->name('membership-check');
});

Modules/Inventory/Entities/Membership.php
<?php

namespace Modules\Inventory\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Inventory\Entities\Card;
class Membership extends Model
{

    protected $fillable = ['name','min_amt','max_amt','status','amount_to_point','short_name','other_information'];
    
    public function cards(){
        return $this->hasMany(Card::class,'membership_id');
    }
    
}

Modules/Inventory/Http/Controllers/MembershipController.php
<?php

namespace Modules\Inventory\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Inventory\Http\Requests\MembershipRequest;
use Modules\Inventory\Interfaces\MembershipInterface;
use Exception;
use Illuminate\Support\Facades\DB;
use Modules\Inventory\Helpers\MembershipShortNameHelper;

class MembershipController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function __construct(MembershipInterface $membershipInterface)
    {
        $this->membershipInterface=$membershipInterface;
    }
    public function index()
    {
        $data['membership']=$this->membershipInterface->getAll();
        return view('inventory::membership.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('inventory::membership.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(MembershipRequest $request)
    {
        try{
            DB::beginTransaction();
            
            $membership=$this->membershipInterface->store($request->all());
        }catch(Exception $e){

            DB::rollback();
            
            return response($e->getMessage());
        }
        DB::commit();
        return redirect()->route('membership.index')->with('message', 'Successfully Created New Privilege Card');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('inventory::membership.show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $data['membership']=$this->membershipInterface->findOrFail($id);
        return view('inventory::membership.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(MembershipRequest $request, $id)
    {
        try{
            DB::beginTransaction();
            $membership=$this->membershipInterface->update($request->all(),$id);
        }catch(Exception $e){

            DB::rollback();
            
            return response($e->getMessage());
        }
        DB::commit();
        return redirect()->route('membership.index')->with('message', 'Successfully Updated The Privilege Card');
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        try{
            $this->membershipInterface->delete($id);
        }catch(Exception $e){
            return response($e->getMessage());
        }
        return redirect()->route('membership.index')->with('message','Privilege Card Deleted Successfully');
    }
}

Modules/Inventory/Resources/views/membership/common.blade.php
{{-- @dd($customer) --}}
<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-5 col-form-label">Privilege Card Name <span class="redAstrick"> *</span>:</label>
            <div class="col-sm-7">
                {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Full Name','data-parsley-trigger'=>'keyup','required']) !!}


            </div>
        </div>
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-5 col-form-label">Min Amount<span class="redAstrick"> *</span>:</label>
            <div class="col-sm-7">
                {!! Form::text('min_amt', null, ['class' => 'form-control', 'id' => 'min_amt', 'placeholder' => 'Min Amount','data-parsley-trigger'=>'keyup','required','data-parsley-type'=>'number']) !!}
            </div>
        </div>
        
        
    </div>
    <div class="col-md-6">
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-6 col-form-label">Short Name<span class="redAstrick"><small><i>(can be auto generated)</i></small></span>:</label>
            <div class="col-sm-6">
                {!! Form::text('short_name', null, ['class' => 'form-control', 'id' => 'short_name', 'placeholder' => 'Short Name','data-parsley-trigger'=>'keyup']) !!}
            </div>
        </div>
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-5 col-form-label">Max Amount<span class="redAstrick"> *</span>:</label>
            <div class="col-sm-7">
                {!! Form::text('max_amt', null, ['class' => 'form-control', 'id' => 'max_amt', 'placeholder' => 'Max Amount','data-parsley-trigger'=>'keyup','required','data-parsley-type'=>'number']) !!}
            </div>
        </div>
        
        
        
    </div>
    <div class="form-group row col-12">
        <label for="inputEmail3" class="col-sm-6 col-form-label">Amount to Reward Conversion <small class="redAstrick"><i>(how much amount is equal to 1 Reward Point???)</i></small><span class="redAstrick"> *</span>:</label>
        <div class="col-sm-6">
            {!! Form::text('amount_to_point', null, ['class' => 'form-control', 'id' => 'amount_to_point', 'placeholder' => 'Amount To Reward Point Conversion','data-parsley-trigger'=>'keyup','required','data-parsley-type'=>'number' ]) !!}
        </div>
    </div>
    <div class="form-group mb-0 justify-content-end row col-12">
        <div class="col-sm-9">
            <button type="submit" class="btn btn-info waves-effect waves-light float-right">Submit</button>
        </div>
    </div>
</div>

Modules/Inventory/Resources/views/membership/create.blade.php
@extends('dashboard::newLayouts.master')
@section('title')
    Customer Create
@endsection
@section('content')
<div class="container-fluid flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>

                <li class="breadcrumb-item"><a href="{{ route('purchase.index') }}">Purchases</a></li>
                <li class="breadcrumb-item active">Create Purchase</li>
            </ol>
        </div>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="col-12">
            <div class="card-box">
                <h4 class="mt-0 mb-3 header-title">Privilege Card Details</h4>
                {!! Form::open(['route' => 'membership.store', 'method' => 'post', 'class' => 'needs-validation form-horizontal membershipForm', 'novalidate','id'=>'formValidation']) !!}
                @include('inventory::membership.common')
                {!! Form::close() !!}
            </div> <!-- end card-box -->
        </div>
    </div>
    </div>
@endsection
@section('script')

@endsection

Modules/Inventory/Resources/views/membership/edit.blade.php
@extends('dashboard::newLayouts.master')
@section('title')
    Edit Privilege Card - {{ $membership->name }}
@endsection
@section('content')
    {{-- @dd($customer) --}}
    <div class="container-fluid flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>

                <li class="breadcrumb-item"><a href="{{ route('membership.index') }}">Privilege Card</a></li>
                <li class="breadcrumb-item active">{{ $membership->name }}</li>
            </ol>
        </div>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="col-12">
            <div class="card-box">
                <h4 class="mt-0 mb-3 header-title">Edit Privilege Card</h4>
                {!! Form::model($membership, ['route' => ['membership.update', $membership->id], 'method' => 'post', 'class' => 'needs-validation form-horizontal', 'novalidate', 'id' => 'formValidation']) !!}
                @method('PATCH')
                @include('inventory::membership.common')
                {!! Form::close() !!}
            </div> <!-- end card-box -->
        </div>
    </div>
    </div>
@endsection
@section('script')
@endsection

Modules/Inventory/Resources/views/membership/index.blade.php
@extends('dashboard::newLayouts.master')
@section('title')
    Privilege Cards
@endsection
@section('style')
    <!-- third party css -->
    <link href="{{ Module::asset('dashboard:libs/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ Module::asset('dashboard:libs/datatables/responsive.bootstrap4.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ Module::asset('dashboard:libs/datatables/buttons.bootstrap4.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ Module::asset('dashboard:libs/datatables/select.bootstrap4.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"
        type="text/css" />
    <!-- third party css end -->
@endsection
@section('content')
<div class="container-fluid flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>

                <li class="breadcrumb-item active">Privilege Card</li>
            </ol>
        </div>
        <div class="col-12">
            <div class="card-box table-responsive">
                <h4 class="mt-0 header-title">Privilege Cards</h4>
                {{-- <p class="text-muted font-14 mb-3">
                    Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
                </p> --}}

                <table id="responsive-customers" class="table table-bordered table-bordered dt-responsive nowrap">
                    {{-- @can('create', [Modules\Inventory\Entities\Customer::class, Modules\AccessManagement\Enums\ModulesEnum::Customer]) --}}
                    <a class="btn btn-sm btn-info float-right" href="{{ route('membership.create') }}"> <i
                            class="fa fa-plus"> </i> </a>
                    {{-- @endcan --}}

                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Short Name</th>
                            <th>Min. Amount</th>
                            <th>Max. Amount</th>
                            <th>Amount To Reward Point</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($membership as $membership)
                            <tr>
                                <td>{{ $loop->index + 1 }}</td>
                                <td>{{ $membership->name }}</td>
                                <td>{{ $membership->short_name }}</td>
                                <td>Rs. {{ $membership->min_amt }}</td>
                                <td>Rs. {{ $membership->max_amt }}</td>
                                <td>Rs. {{ $membership->amount_to_point }}</td>
                                <td>
                                    <a class="btn btn-info btn-sm " href="{{route('membership.edit',$membership->id)}}"
                                        >
                                        <i class="fa fa-edit">
                                        </i>
                                    </a>
                                    <a href="javascript:void(0);" class="btn btn-sm btn-danger delete"
                                                data-id="{{ $membership->id }}"><i class="fas fa-trash"></i></a>
                                            &nbsp; &nbsp;
                                            <form class="postdestroy" id="form_{{ $membership->id }}" style="margin: 0;"
                                                method="Post" action="{{ route('membership.destroy', $membership->id) }}"
                                                data-toggle="modal" data-target="#exampleModal">
                                                @csrf
                                                @method('Delete')
                                            </form>



                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- end row -->
    </div> <!-- end row -->
@endsection
@section('script')
    <!-- third party js -->
    <script src="{{ Module::asset('dashboard:libs/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.responsive.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.buttons.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/buttons.html5.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/buttons.flash.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/buttons.print.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/datatables/dataTables.select.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/pdfmake/pdfmake.min.js') }}"></script>
    <script src="{{ Module::asset('dashboard:libs/pdfmake/vfs_fonts.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <!-- third party js ends -->
    <script>
        $(document).ready(function() {

            $('#responsive-customers').DataTable();
            @if (Session::has('message'))
                toastr.success('{{ Session::get('message') }}')
            @endif
            @if (Session::has('error'))
                toastr.warning('{{ Session::get('error') }}')
            @endif
            $(document).on('click', '.delete', function() {
                id = $(this).data('id');
                swal({
                        title: "Are you sure?",
                        text: "Once deleted, you will not be able to recover this data!",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (willDelete) {
                            $('#form_' + id).submit();
                            swal("Poof! Your record has been deleted!", {
                                icon: "success",

                            });
                        } else {
                            swal("Deleting Data Cancled!!");
                        }
                    });
            })

        })
    </script>
@endsection

Modules/Inventory/Resources/views/membership/show.blade.php
@extends('dashboard::newLayouts.master')
@section('title')
    Customer Details- {{ $customer->name }}
@endsection
@section('content')
    {{-- @dd($customer) --}}
    <div class="container-fluid flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Dashboard</a></li>

                <li class="breadcrumb-item "><a href="{{ route('dashboard.index') }}">Customers</a></li>
                <li class="breadcrumb-item active">{{ $customer->name }}</li>
            </ol>
        </div>
        <div class="col-12">
            <div class="card-box task-detail">
                
                <div class="row task-dates mb-0 mt-2">
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Customer Name</h5>
                        <p> {{ $customer->name }} <small class="text-muted"></small></p>
                    </div>

                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Phone No.</h5>
                        <p> {{ $customer->phone }} <small class="text-muted"></small></p>
                    </div>
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Email</h5>
                        <p>{{ $customer->email }}</p>
                    </div>

                </div>
                <div class="row task-dates mb-0 mt-2">
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Address</h5>
                        <p> {{ $customer->address }}
                            <small class="text-muted"></small>
                        </p>
                    </div>

                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Aniversary Date</h5>
                        <p>{{ $customer->customerDetails->aniversary_date }} <small class="text-muted"></small>
                        </p>
                    </div>
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Spouse Name</h5>
                        <p> {{ $customer->customerDetails->spouse_name }} <small class="text-muted">g</small></p>
                    </div>
                </div>
                <div class="row task-dates mb-0 mt-2">
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Birth Date</h5>
                        <p> {{ $customer->customerDetails->birth_date }}
                            <small class="text-muted"></small>
                        </p>
                    </div>

                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Mobile</h5>
                        <p> {{ $customer->customerDetails->mobile }}</p>
                    </div>
                    <div class="col-lg-4">
                        <h5 class="font-600 m-b-5">Designation</h5>
                        <p>{{ $customer->customerDetails->designation }}</p>
                    </div>
                </div>

                <hr>
                <div class="form-group mb-0 justify-content-end row">
                    <div class="col-sm-9">
                        <a href="{{route('customers.index')}}" class="btn btn-info waves-effect waves-light float-right">Back</a>
                        <a href="{{route('customers.edit',$customer->id)}}" class="btn btn-warning waves-effect waves-light float-right mr-2" style="color:black;">Update</a>
                    </div>
                </div>

            </div>
        </div><!-- end col -->

    </div>
    </div>
    <!-- end row -->
@endsection